site_name: twars-url2md Documentation
site_description: A powerful CLI tool that fetches web pages and converts them to clean Markdown format
site_author: Adam Twardoch
site_url: https://twardoch.github.io/twars-url2md/

repo_name: twardoch/twars-url2md
repo_url: https://github.com/twardoch/twars-url2md
edit_uri: edit/main/src_docs/md/

theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      title: On this page
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: twardoch
      repo: twars-url2md
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - User Guide:
    - Basic Usage: usage.md
    - Advanced Features: advanced.md
    - Configuration: configuration.md
  - Development:
    - Architecture: architecture.md
    - Contributing: contributing.md
    - Testing: testing.md
    - API Reference: api.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/twardoch/twars-url2md
    - icon: fontawesome/brands/rust
      link: https://crates.io/crates/twars-url2md

copyright: Copyright &copy; 2024 Adam Twardoch. Licensed under MIT License.

# Custom CSS
extra_css:
  - assets/extra.css

# Custom JavaScript  
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

docs_dir: md
site_dir: ../docs